# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Dev Dark Theme

# meta tags
charset: utf-8
robots: index, follow
keywords: Dev-Dark-Theme, DevDarkTheme, Hexo, Theme, Dev, Dark, Theme
content: The dev dark theme is a theme developed by Marcos Gonçalves(codermarcos) using hexo.
author: codermarcos

# Locale
language: pt
date_format: YYYY-MM-DD
time_format: HH:mm:ss

sitemap:
    path: sitemap.xml
    template: ./sitemap_template.xml
    tag: true
    category: true

# Show comments
## Docs: https://developers.facebook.com/tools/comments/
comments:
  show: true
  script_discus: https://dev-dark-theme.disqus.com/embed.js

# Inline css
inline_assets:
  enabled: true
  limit: 100000

# RSS
feed:
  type: atom
  path: 'atom.xml'
  limit: 8
  hub: 
  content:
  content_limit: 140
  content_limit_delim: ' '

# hexo-generator-amp
# The following settings is the quick start options.

generator_amp:
  templateDir:  amp-template
  assetDistDir: amp-dist
  logo:
    path:   sample/sample-logo.png
    width:  600
    height: 60
  substituteTitleImage:
    path:   sample/sample-substituteTitleImage.png
    width:  1024
    height: 800
  warningLog: false   # To display warning, please set true.

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://dev-dark-theme.codermarcos.com
root: /
permalink: :lang/:category/:title/
permalink_defaults: 
  lang: pt

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :lang/:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 4
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Pagination
## Set per_page to 0 to disable pagination
per_page: 4
pagination_dir: lasts

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: dev-dark-theme

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/codermarcos/dev-dark-theme
  branch: gh-pages
  message: "Deploy theme: {{ now('YYYY-MM-DD HH:mm:ss') }})"

