# Miscellaneous
analytics: UA-106429071-3
favicon: /favicon.png
twitter: https://twitter.com/codermarcos
gmail: mailto:coder.marcos@gmail.com
github: https://github.com/codermarcos/dev-dark-theme
facebook:
instagram:
linkedin: https://br.linkedin.com/in/codermarcos
youtube:
whatsapp: https://api.whatsapp.com/send?phone=5511971353293